### ISSUE TITLE
S4AHK.patch

### ISSUE THREAD

**Issue by Lexikos** [fincs/SciTE4AutoHotkey#10]
S4AHK.patch shows changes to closefile.bmp and a new file, closefile_big.bmp, but cannot possibly be used to apply these changes.  Consequently, applying the patch as per the instructions leaves me with code that will not compile.

For now I've just copied closefile.bmp, as I couldn't care less about high DPI images.

**Comment by fincs** [comment]
[SciTE/Scintilla/Lexilla patches](https://github.com/fincs/SciTE4AutoHotkey/tree/master/scipatches) have been refactored for greater reproducibility.
