### ISSUE TITLE
Some Chinese Characters are recognized as numbers due to custom SciLexer.dll

### ISSUE THREAD

**Issue by daviduuang** [fincs/SciTE4AutoHotkey#13]
I found that some Chinese Characters are recognized  as numbers, because the highlighted chars have the same style with numbers in ahk source.

Not all styles in sciTE4AutoHotKey can reveal the issue, because numbers setting in some style are the same common chars(untyped parameters).  In the other words, different styles setting can't result  in this issue.

You can try the Monokai.style.properties in "Styles" folder, and with the ahk code below:
===============code start=======================
Gui, Add, Button, xp yp+60 wp hp , 读取记录
Gui, Add, Button, xp yp+60 wp hp , 导出记录
Gui, Add, Button, xp yp+60 wp hp , 断开连接
Gui, Add, ListView, x120 y130 w500 h315 , ListView
Gui, Add, Progress, xp y445 w500 h10 , 25

Gui, Tab, 2
gui, add, text, x10 y135 w30 h20, 日期
Gui, Add, DateTime, xp+35 yp-5 w90 h20 vdate, yyyy-MM-dd
gui, add, text, xp+100 yp+5 w30 h20, 槽号
===============code end=======================

Later, I try another custom sciTE with simple autohotkey support(although its package name is sciTE4AutoHotkey.rar). And I found it have no issue for this. Then I replace its SciLexer.dll with the sciTE4AutoHotkey's, the issue recur. So I think maybe there is some bug in SciLexer.dll for sciTE4AutoHotKey(fincs).
You can get it here:https://app.box.com/shared/xn4apnatc9

Some pictures attached below:
pic 1(OK, custom sciTE with simple autohotkey support using VimEvening style )
![1](https://f.cloud.github.com/assets/5523894/1825635/321bf3d6-71c8-11e3-89c1-3ef323b8812e.png)

pic2(not OK, fincs' sciTE4AutoHotKey with VimEvening.style.properties by me )
![2](https://f.cloud.github.com/assets/5523894/1825637/462c6702-71c8-11e3-9076-4dbb164a19ee.png)

You can get VimEvening.style.properties here: https://www.dropbox.com/s/li6e2j2guuzjzux/VimEvening.style.properties

**Comment by fincs** [comment]
Closing due to S4AHK v3.1.0 upgrading to more recent SciTE/Scintilla releases.
