### ISSUE TITLE
ActiveWindowInfo.ahk - Specifies tray icon when #NoTrayIcon is enabled?

### ISSUE THREAD

**Issue by joedf** [fincs/SciTE4AutoHotkey#16]
Why specify the tray icon, if `#NoTrayIcon` is specified?

File: "**ActiveWindowInfo.ahk**"
```AutoHotkey
#NoTrayIcon
#SingleInstance Ignore
SetWorkingDir, %A_ScriptDir%
SetBatchLines, -1
CoordMode, Pixel, Screen
IfExist, ..\toolicon.icl ; Seems useful enough to support standalone operation.
Menu, Tray, Icon, ..\toolicon.icl, 9
```
Code in question : [Permalink](https://github.com/fincs/SciTE4AutoHotkey/blob/8e757d0559bcec4e37962e8699a4765e5cb83e99/source/tools/ActiveWindowInfo.ahk#L6-L13)

**Comment by fincs** [comment]
Not a bug. This is used to change the window icon of Guis when launched from SciTE4AutoHotkey.

**Comment by joedf** [comment]
ahh, ok. simply curious.
