### ISSUE TITLE
plz put in korean locale your project

### ISSUE THREAD

**Issue by hjhj3686** [fincs/SciTE4AutoHotkey#17]
korean(한국어) locale files dl link : https://drive.google.com/file/d/0BwSPQJyiXhWQUDlMWThma2lvRE0/view?usp=sharing

The creators of this file joyfui
Please add it to your project for him.
http://joyfui.wo.tc/834

**Comment by fincs** [comment]
Thanks for your contribution. The next version of SciTE4AutoHotkey will come with joyfui's Korean translation.
