### ISSUE TITLE
Update notification when website is down

### ISSUE THREAD

**Issue by thisischrys** [fincs/SciTE4AutoHotkey#24]
The website is down right now and every time I start SciTE4AutoHotkey it tells me there is an update.

**Comment by soulomoon** [comment]
The website is down, wondering why?

**Comment by joedf** [comment]
fincs is unavailable, possibly busy or too much stuff on his mind.
quick fix from here: https://autohotkey.com/boards/viewtopic.php?p=104496#p104496
turn off automatic update checks:
`Options -> Open User properties`
then add the following.
```
# Enable/disable SciTE4AutoHotkey automatic updates  
automatic.updates=0
```

**Comment by fincs** [comment]
See f13865dcea. Also fincs.ahk4.net is back up.
