### ISSUE TITLE
Crash during program start up

### ISSUE THREAD

**Issue by devdel** [fincs/SciTE4AutoHotkey#27]
I don't remember doing anything to my system that might cause this. But now, whenever I try to start the SciTE4AutoHotkey I get these error messages and the program cashes.

I'm running Windows 7 Ultimate x64.

Here's the information given in the "View problem details".
"Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	SciTE.exe
  Application Version:	3.0.6.1
  Application Timestamp:	543adcef
  Fault Module Name:	SciLexer.DLL
  Fault Module Version:	3.5.1.0
  Fault Module Timestamp:	543a6894
  Exception Code:	c0000005
  Exception Offset:	000c9f7e
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1053
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt"

Then there are popup messages...
The first one is "popup.error.01.jpg"
The second one is "popup.error.02.if.yes.on.error.01.jpg"

I've uninstalled and reinstalled the program but that made no difference.
Please help.

Thanks in advance,
Kind regards

![popup error 01](https://user-images.githubusercontent.com/20277490/41942152-b478c9c0-799e-11e8-9999-7af8bd30777c.jpg)
![popup error 02 if yes on error 01](https://user-images.githubusercontent.com/20277490/41942160-ba98b3ce-799e-11e8-938e-d71a7c339842.jpg)

**Comment by fincs** [comment]
[Please try again with the latest release](https://github.com/fincs/SciTE4AutoHotkey/releases/tag/v3.1.0).
