### ISSUE TITLE
Is this work?

### ISSUE THREAD

**Issue by rediffusion** [fincs/SciTE4AutoHotkey#29]
How can I install it? When I run "\SciTE4AutoHotkey-master\installer\setup.ahk" I see this MsgBox "Oops `;p" -- whats that means?
I try downloading from other [link](http://fincs.ahk4.net/scite4ahk/) and it works now.
I just want to know what is the problem here?

**Comment by fincs** [comment]
You attempted to run the uncompiled copy of the installer. If you want to install S4AHK, please use [the official installer](https://www.autohotkey.com/scite4ahk/dl/s4ahk-install.exe).
