### ISSUE TITLE
Keep getting the same error code when I try to run a script within the application.

### ISSUE THREAD

**Issue by NotNotJustin** [fincs/SciTE4AutoHotkey#30]
`"C:\Program Files\AutoHotkey\AutoHotkey.exe" /ErrorStdOut "~\Desktop\Folder\Script.ahk"`

**Comment by NotNotJustin** [comment]
I don't plan on continuing to work on any more AHK Scripts, including the one I was having problems with, but I won't close the issue just in case somebody else is having the same problem as I was.

**Comment by joedf** [comment]
perhaps you could share a screenshot and an example script? just in case

**Comment by NotNotJustin** [comment]
The code is available at https://github.com/NotNotJustin/xisumavoids-world-pregen-by-nnj . I figured out that the latest AHK version wasn't working with the debugger and that there were modified SciTE4AHK program files that would fix this.

**Comment by NotNotJustin** [comment]
The solution was here: https://github.com/fincs/SciTE4AutoHotkey/issues/23#issuecomment-280170712
