### ISSUE TITLE
Extremely useful tool

### ISSUE THREAD

**Issue by wysnxzm** [fincs/SciTE4AutoHotkey#33]
The best AutoHotkey editor
Unfortunately, there is no update

**Comment by fincs** [comment]
[Now there is](https://github.com/fincs/SciTE4AutoHotkey/releases/tag/v3.1.0)

**Comment by wysnxzm** [comment]
brother this cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool ! cool !
