### ISSUE TITLE
Wingget

### ISSUE THREAD

**Issue by salarmehr** [fincs/SciTE4AutoHotkey#34]
Could this excellent IDE be added to winget, 
I can install ahk by `winget install ahk` but I cannot install scite4ahk by `winget install scite4ahk`.

**Comment by fincs** [comment]
Third party package managers are neither supported nor recommended. The only supported official way to install S4AHK is directly through [the installer](https://www.autohotkey.com/scite4ahk/dl/s4ahk-install.exe).

**Comment by salarmehr** [comment]
It seems you have not heard about Winget. It uses the installers like what you linked.
