### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by AlexBartles2012** [fincs/SciTE4AutoHotkey#36]
Hey, the website is sold or down so I don't know how to install it. Please help. Thanks!

**Comment by AlexBartles2012** [comment]
I found  the new website.

**Comment by joedf** [comment]
For future readers: 

We do have archived version of the site here:
https://www.autohotkey.com/scite4ahk/

Please note that any update notifications may not be relevant as the official scite4ahk site is down.

**Comment by joedf** [comment]
Maybe put a new release with those update patches applies and auto-updates turned off?
