### ISSUE TITLE
Updated!

### ISSUE THREAD

**Issue by Coldblackice** [fincs/SciTE4AutoHotkey#38]
I just arrived here to reinstall SciTE4AHK after a machine reformat, expecting to find the near decade old latest version -- and perfectly okay with that -- ...only to do a literal double-take when I saw the most recent release was just four days ago. I had to check what repo I was on, thinking maybe I was at the wrong place. But nope. It's like waking up on Christmas morning!

I've been playing around with the update, and it's awesome: so much snappier now, the feature/function additions are great, and it looks fantastic. Thanks a ton for the update!

**Comment by fincs** [comment]
This is not actually an issue report (and as such [the forum thread](https://www.autohotkey.com/boards/viewtopic.php?f=61&t=104086) would have been a better place to post it), but regardless I'm happy this new release of S4AHK pleased you :)
