### ISSUE TITLE
It's good to see you back. 

### ISSUE THREAD

**Issue by telppa** [fincs/SciTE4AutoHotkey#39]
Hi fincs , thank you for creating this great tool, I've been using it for over 10 years and it's great to see you back.

For the past 8 years, I've thought you were no longer updating, so I created a branch with many, many, many fixes and improvements.

I thought we could discuss how to merge these updates in order to eliminate a lot of needless duplication of effort.

Here is my version(Sorry, I didn't expect you to come back, so some of the code isn't written in English, but it should still work fine.)

[https://github.com/telppa/SciTE4AutoHotkey-Plus](https://github.com/telppa/SciTE4AutoHotkey-Plus)

**Comment by fincs** [comment]
Thanks for being a long-time user of S4AHK. Unfortunately it looks like your fork is not in a state that can be easily compared to my upstream, nor is it even a direct fork of this repository. Moreover, it also looks like your fork is specifically geared towards the Chinese-speaking AutoHotkey community; and I'm having trouble figuring out what it is that you have changed. With that said, I'm open to discussing piecemeal pull requests, though.
