### ISSUE TITLE
syntax highlight error

### ISSUE THREAD

**Issue by telppa** [fincs/SciTE4AutoHotkey#40]
here is test code

```
字符串=   ; this is string
(
abc
def
)

字符串2=  ; this is string
(%
abc
def
)

标签:    ; this is label
return

abcd:="afeeeeee

返回值1:=abc.Value1
返回值2:=WinHttp.URLDownloadToFile(网址, ID ".txt", 设置, 请求头)

Gui Add, Edit, x464 y528 w55 h21 v纸费_ g计算段, 3.5
MsgBox, 4148, 提示, 本工具将关闭Flash的P2P功能，以便释放上传通道，最终加速视频网站播放速度！`r`n`r`n适用于优酷、爱奇艺、搜狐、乐视、土豆等几乎所有视频网站。
FileCreateDir, %A_AppData%\SogouExplorer\Webkit\Default\Pepper Data\Shockwave Flash\system

^+Up::
#x::
GuiClose:
return

parsed_out := Format("      ; this is string
(Join`r`n
String: {}
Number: {}
Float:  {}
true:   {}
false:  {}
null:   {}
array:  [{}, {}, {}]
object: {{}A:""{}"", H:""{}"", K:""{}""{}}
)"

```

![1](https://user-images.githubusercontent.com/68984587/170187847-3f5fa516-2c09-4e13-83ba-9ef68e1cf987.png)
![2](https://user-images.githubusercontent.com/68984587/170187858-010567dd-0868-42c1-a5ea-ea53f3e8528d.png)

**Comment by fincs** [comment]
The AutoHotkey v1 lexer is very old and no longer maintained, and it is also well known to have many problems stemming from AHKv1's syntax being very ambiguous and difficult to parse reliably. On the other hand, the AutoHotkey v2 lexer does not present these kinds of issues.
