### ISSUE TITLE
is keyword parameter tooltip removed?

### ISSUE THREAD

**Issue by devPnal** [fincs/SciTE4AutoHotkey#41]
Hi,

when v3.0.06, I can use the 'parameter tooltip' like below

![image](https://user-images.githubusercontent.com/102811808/170818500-ba79c4c0-05fe-4809-9186-5352af5330a6.png)

I think that feature served by this ahk.api file ▼
https://github.com/fincs/SciTE4AutoHotkey/blob/76b27763c160e05f3ae32121af88544b12dff4be/source/ahk.api

but in v3.1.0, the file removed, and new [ahk1.standard.api] file created. This file doesn't contain parameter description ▼
https://github.com/fincs/SciTE4AutoHotkey/blob/master/source/ahk1.standard.api

I can't use that feature anymore. did you intend?
if not, (I mean, If it's just a bug,) how can I solve this issue?

It's just tiny issue, but I just submit it.

Sorry for broken English.

**Comment by fincs** [comment]
Unfortunately this is a known issue.

> Calltip functionality has been temporarily removed as a side effect of the new syntax definition autogeneration, as well as SciTE limitations.

This feature will be brought back at a later date, but this needs further development in the script that extracts syntax information from the AHK documentation.
