### ISSUE TITLE
How can I view the lexer logic?

### ISSUE THREAD

**Issue by mark-wiemer** [fincs/SciTE4AutoHotkey#42]
Hi @fincs, first off, this is an amazing project. Kudos to you for maintaining it so well for so long.

I'm hoping to incorporate a syntax highlighter and formatter into VS Code. I'm still in the research phase, but I saw your changelog mentioned a "completely rewritten new lexer". Where can I find this lexer? A quick search hasn't been so helpful. I'd really appreciate your help here!

If you're curious, you can track my progress at [ahk++ - fix the syntax highlighter](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/128).

**Comment by fincs** [comment]
The source code for the SciTE/Scintilla/Lexilla patches [have always been available in this repo](https://github.com/fincs/SciTE4AutoHotkey/tree/master/scipatches), but now that Lexilla is a separate project hosted on GitHub, I've decided to [push my code directly as a fork](https://github.com/fincs/lexilla-s4ahk/blob/s4ahk/lexers/LexAHK2.cxx).
